# Generated by Django 5.2.7 on 2025-10-04 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('articulo_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_articulo', models.CharField(max_length=25, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=25, null=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulos',
            },
        ),
        migrations.AlterModelOptions(
            name='grupoarticulo',
            options={'verbose_name': 'Grupo de Artículo', 'verbose_name_plural': 'Grupos de Artículos'},
        ),
        migrations.AlterModelOptions(
            name='lineaarticulo',
            options={'verbose_name': 'Línea de Artículo', 'verbose_name_plural': 'Líneas de Artículos'},
        ),
        migrations.RemoveField(
            model_name='grupoarticulo',
            name='codigo_grupo',
        ),
        migrations.RemoveField(
            model_name='lineaarticulo',
            name='codigo_linea',
        ),
        migrations.AlterField(
            model_name='lineaarticulo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='core.grupoarticulo'),
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('articulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='listaprecio', serialize=False, to='core.articulo')),
                ('precio_1', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_2', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_3', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_4', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Lista de Precio',
                'verbose_name_plural': 'Listas de Precios',
                'db_table': 'lista_precios',
            },
        ),
        migrations.AddField(
            model_name='articulo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.grupoarticulo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.lineaarticulo'),
        ),
    ]
